config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  # get "/posts", to: "posts#index"
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= comment.body  %><br>
<strong> <%= comment.commenter  %></strong><br><br>

Commented: <%= time_ago_in_words(comment.created_at) %> ago
<%= link_to "Delete comment", post_comment_path(@post, comment), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %><hr>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build] do |form| %>
  <div>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </div>

  <br><br>
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render partial: "shared/navbar" %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <br><br>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>
  <br>

  <div>
    <%= form.submit %>
  </div>
  <br>

  <h4><%= "Error creating post" if post.errors.any? %><br></h4>
  <div style="color: red" >
    <% post.errors.each do |error| %>
      <%= error.full_message %><br>
    <% end %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class = "d-flex align-items-center justify-content-center">
  <h1>Welcome to Socialite</h1>
</div>


<button><%= link_to "Create New Post", new_post_path %></button><br>
<br>

<% @posts.each do |post|%>
  <div class="post_wrapper">
    <h2 class="title"><%= post.title%></h2>
    <p class="date"><%= post.created_at.strftime('%B %d, %Y')%></p>
    <p> Caption: <%= post.body %></p>

    <%= link_to "See post", post_path(post) %> &emsp;
    <%= link_to "Edit post", edit_post_path(post) %> &emsp;
    <%= link_to "Delete post", post_path(post), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
    <hr> <br>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class = "d-flex align-items-center justify-content-left">
  <h2>Create New Post</h2>
</div>


<%= render "form", post: @post %>

app/views/posts/show.html.erb
<p class="title">
  <h2> <%= @post.title %></h2>
</p>

<p class = "date" style = "font-style: italic">
  Submitted: <%= time_ago_in_words(@post.created_at) %> ago
</p>

<p class = "body">
  Caption: <%= @post.body %>
</p>

<%= link_to "Edit post", edit_post_path(@post) %> &emsp;

<%= link_to "Delete post", post_path(@post), data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"
} %>

<br><br>

<h2><%= @post.comments.count %> Comments</h2>

<!--this will render the "app/views/comments/_comment.html.erb" file-->
<!--for each iteration of the collection @post.comments-->
<%= render @post.comments %>

<h2>Add a comment:</h2>
<div class = "container">
  <%= render "comments/form" %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md sticky-top navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand">Socialite</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create New Post", new_post_path, class: "nav-link" %>
        </li>
      </ul>

      <ul class="nav nav-pills ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item navbar-text ">
            Logged in as: <b><%= current_user.email %></b>
          </li>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_user_session_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= button_to "Sign In", new_user_session_path, class: "nav-link active" %>
          </li>
          <li class="nav-item pl-2">
            <%= link_to "Sign Up", '/users/sign_up', class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>